# Generated by Django 5.1.4 on 2025-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.FloatField(help_text='Quantidade de milímetros (mm) de chuva. Exemplo: 25 ou 25,3 ')),
                ('data', models.DateField(unique=True, verbose_name='Data de chuva')),
            ],
            options={
                'verbose_name': 'Chuva',
                'verbose_name_plural': 'Chuvas',
            },
        ),
    ]
