# Generated by Django 5.1.4 on 2025-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHasse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuva',
            name='data',
            field=models.DateField(unique=True, verbose_name='data de chuva'),
        ),
        migrations.AlterField(
            model_name='chuva',
            name='qtd',
            field=models.IntegerField(help_text='Quantidade de milímetros (mm) de chuva. Exemplo: 25', verbose_name='quantidade de chuva (mm)'),
        ),
    ]
