# Generated by Django 5.1.4 on 2025-01-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHasse', '0002_alter_chuva_data_alter_chuva_qtd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chuva',
            new_name='Clima',
        ),
    ]
