# Generated by Django 5.1.4 on 2025-01-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHasse', '0003_rename_chuva_clima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clima',
            options={'verbose_name': 'Clima', 'verbose_name_plural': 'Climas'},
        ),
    ]
